data:
  url1: http://192.168.1.110:4200
  url2: http://192.168.1.110:80
  url_oa: "/api/staff/login.json"
  url_financial: "/api/oaSystem/login.json"
  username: 15700009999
  password: mQAdelhBxWqt/y380cjUVoydl+c=


